model:
  autoencoder_cfg:
    in_channels: 3
    channels:
      - 16
    dim_keys: 64
    n_heads: 4

  latent_dim: 10
  n_embeddings: 256

loss:
  rec_loss_type: 'L2'
  perceptual_weight: 0.1
  codebook_weight: 0.9
  commitment_weight: 0.25
  disc_weight: 0.1
  disc_in_channels: 3
  disc_n_layers: 2
  disc_warm_up_iters: 1000
  disc_res_blocks: False
