loss:
  codebook_weight: 0.9
  commitment_weight: 0.25
  disc_in_channels: 3
  disc_n_layers: 4
  disc_res_blocks: false
  disc_warm_up_iters: 5000
  disc_weight: 0.1
  perceptual_weight: 0.1
  rec_loss_type: L1
model:
  autoencoder_cfg:
    channels:
    - 32
    - 64
    dim_keys: 64
    in_channels: 3
    n_heads: 4
  latent_dim: 32
  n_embeddings: 512
