model:
  in_channels: 3
  latent_dim: 10

  # settings for residual blocks
  n_res_layers: 2
  res_hidden_dim: 256

  # settings for embedding
  n_embeddings: 512

loss:
  rec_loss_type: 'L1'
  perceptual_weight: 0
  codebook_weight: 1
  commitment_weight: 0.25
  disc_weight: 0